import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { globMatches, loadProjectConfig, RiskConfig, runConfiguredCommand, runtimeStateIgnoreEntries, VerificationError } from "./verification.js";
import { StorageMode, workspaceFor } from "./storage.js";

export interface InitResult { path: string; verify: string[]; config: string; created: true; gitignoreAdded: string[]; trackedRuntimePaths: string[]; }
export interface DoctorResult { status: "passed" | "warning"; modules: Array<{ name: string; matchedPaths: number; commands: Array<{ command: string; status: "passed" }> }>; risks: RiskConfig[]; warnings: string[]; }

function detectedCommand(root: string): string[] {
  if (existsSync(join(root, "gradlew"))) return ["./gradlew test"];
  if (existsSync(join(root, "mvnw"))) return ["./mvnw test"];
  const packagePath = join(root, "package.json");
  if (existsSync(packagePath)) { try { if (JSON.parse(readFileSync(packagePath, "utf8")).scripts?.test) return ["npm test"]; } catch {} }
  if (existsSync(join(root, "pyproject.toml"))) return ["pytest -q"];
  if (existsSync(join(root, "go.mod"))) return ["go test ./..."];
  if (existsSync(join(root, "Cargo.toml"))) return ["cargo test"];
  return [];
}

function missingRuntimeIgnoreEntries(root: string): string[] {
  const gitignore = join(root, ".gitignore");
  const lines = existsSync(gitignore) ? readFileSync(gitignore, "utf8").split(/\r?\n/).map((line) => line.trim()) : [];
  return runtimeStateIgnoreEntries.filter((entry) => !lines.includes(entry) && !lines.includes(".telos/") && !lines.includes(".telos/**"));
}

function addRuntimeIgnoreEntries(root: string): string[] {
  const missing = missingRuntimeIgnoreEntries(root);
  if (!missing.length) return [];
  const gitignore = join(root, ".gitignore");
  const existing = existsSync(gitignore) ? readFileSync(gitignore, "utf8") : "";
  writeFileSync(gitignore, `${existing && !existing.endsWith("\n") ? `${existing}\n` : existing}${missing.join("\n")}\n`);
  return missing;
}

function trackedRuntimePaths(root: string): string[] {
  try { return execFileSync("git", ["ls-files", "--cached", "--", ...runtimeStateIgnoreEntries], { cwd: root, encoding: "utf8" }).split(/\r?\n/).filter(Boolean); }
  catch { return []; }
}

export function initProject(root: string, force = false, storage: StorageMode = "global"): InitResult {
  const workspace = workspaceFor(root, storage);
  const path = join(workspace.path, "project.yml");
  if (existsSync(path) && !force) throw new VerificationError(`Telos project configuration already exists at ${path}; use --force to replace it`);
  const verify = detectedCommand(root); const rendered = verify.length ? `[${JSON.stringify(verify[0])}]` : "[]";
  const text = `# Generated by telos init. Verify the detected command before continuing.\nmodules:\n  - name: all\n    paths: [\"**\"]\n    verify: ${rendered}${verify.length ? " # detected from repository markers" : " # manual verification required"}\n`;
  mkdirSync(workspace.path, { recursive: true }); writeFileSync(path, text);
  const gitignoreAdded = workspace.storage === "repository" ? addRuntimeIgnoreEntries(root) : [];
  return { path, verify, config: text, created: true, gitignoreAdded, trackedRuntimePaths: workspace.storage === "repository" ? trackedRuntimePaths(root) : [] };
}

export function doctorProject(root: string, timeout = 600_000): DoctorResult {
  const workspace = workspaceFor(root);
  const config = loadProjectConfig(root);
  let paths: string[];
  try { paths = execFileSync("git", ["ls-files", "--cached", "--others", "--exclude-standard"], { cwd: root, encoding: "utf8" }).split(/\r?\n/).filter(Boolean); }
  catch { throw new VerificationError("telos doctor requires a Git worktree"); }
  const modules = config.modules.map((module) => {
    const matchedPaths = paths.filter((path) => module.paths.some((pattern) => globMatches(pattern, path))).length;
    const commands = module.verify.map((command) => {
      let result;
      try { result = runConfiguredCommand(command, root, timeout); }
      catch (error) { throw new VerificationError(`doctor command could not run for module ${module.name}: ${(error as Error).message}`); }
      if (result.status !== 0) throw new VerificationError(`doctor command failed for module ${module.name}: ${command} (exit ${result.status})${result.detail ? `\n--- output (tail) ---\n${result.detail}` : ""}`);
      return { command, status: "passed" as const };
    });
    return { name: module.name, matchedPaths, commands };
  });
  const missingIgnoreEntries = workspace.storage === "repository" ? missingRuntimeIgnoreEntries(root) : [];
  const tracked = workspace.storage === "repository" ? trackedRuntimePaths(root) : [];
  const warnings = [
    ...missingIgnoreEntries.map((entry) => `${entry} is not ignored; add it to .gitignore so Telos runtime state does not enter Git status.`),
    ...tracked.map((path) => `${path} is Git-tracked; remove it from the index with \`git rm -r --cached ${path}\`.`)
  ];
  return { status: warnings.length ? "warning" : "passed", modules, risks: config.risks, warnings };
}
