import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { globMatches, loadProjectConfig, RiskConfig, runConfiguredCommand, VerificationError } from "./verification.js";

export interface InitResult { path: string; verify: string[]; config: string; created: true; }
export interface DoctorResult { status: "passed"; modules: Array<{ name: string; matchedPaths: number; commands: Array<{ command: string; status: "passed" }> }>; risks: RiskConfig[]; }

function detectedCommand(root: string): string[] {
  if (existsSync(join(root, "gradlew"))) return ["./gradlew test"];
  if (existsSync(join(root, "mvnw"))) return ["./mvnw test"];
  const packagePath = join(root, "package.json");
  if (existsSync(packagePath)) { try { if (JSON.parse(readFileSync(packagePath, "utf8")).scripts?.test) return ["npm test"]; } catch {} }
  if (existsSync(join(root, "pyproject.toml"))) return ["pytest -q"];
  if (existsSync(join(root, "go.mod"))) return ["go test ./..."];
  if (existsSync(join(root, "Cargo.toml"))) return ["cargo test"];
  return [];
}

export function initProject(root: string, force = false): InitResult {
  const path = join(root, ".telos", "project.yml");
  if (existsSync(path) && !force) throw new VerificationError(".telos/project.yml already exists; use --force to replace it");
  const verify = detectedCommand(root); const rendered = verify.length ? `[${JSON.stringify(verify[0])}]` : "[]";
  const text = `# Generated by telos init. Verify the detected command before continuing.\nmodules:\n  - name: all\n    paths: [\"**\"]\n    verify: ${rendered}${verify.length ? " # detected from repository markers" : " # manual verification required"}\n`;
  mkdirSync(join(root, ".telos"), { recursive: true }); writeFileSync(path, text);
  return { path, verify, config: text, created: true };
}

export function doctorProject(root: string, timeout = 600_000): DoctorResult {
  const config = loadProjectConfig(root);
  let paths: string[];
  try { paths = execFileSync("git", ["ls-files", "--cached", "--others", "--exclude-standard"], { cwd: root, encoding: "utf8" }).split(/\r?\n/).filter(Boolean); }
  catch { throw new VerificationError("telos doctor requires a Git worktree"); }
  const modules = config.modules.map((module) => {
    const matchedPaths = paths.filter((path) => module.paths.some((pattern) => globMatches(pattern, path))).length;
    const commands = module.verify.map((command) => {
      let result;
      try { result = runConfiguredCommand(command, root, timeout); }
      catch (error) { throw new VerificationError(`doctor command could not run for module ${module.name}: ${(error as Error).message}`); }
      if (result.status !== 0) throw new VerificationError(`doctor command failed for module ${module.name}: ${command} (exit ${result.status})${result.detail ? `\n--- output (tail) ---\n${result.detail}` : ""}`);
      return { command, status: "passed" as const };
    });
    return { name: module.name, matchedPaths, commands };
  });
  return { status: "passed", modules, risks: config.risks };
}
